#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EightBot.XamarinAndroidProxy.Demo.Resource", IsApplication=true)]

namespace EightBot.XamarinAndroidProxy.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int feedback_ignored_packages = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int wifi_ap_security = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int wifi_eap_method = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int wifi_p2p_status = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int wifi_p2p_wps_setup = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int wifi_security = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int wifi_security_no_eap = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int wifi_status = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int wifi_status_with_ssid = 2131034120;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int state_encrypted = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int available = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int connected = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int direct_connection = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int not_available = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int not_set = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int not_valid_proxy_setting = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int proxy = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int status_description_checking = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int status_description_enabled = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int status_description_invalid_host = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int status_description_invalid_port = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int status_description_not_enabled = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int status_description_not_reachable = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int status_description_web_not_reachable = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int status_exclusion_item_empty = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int status_exclusion_item_notvalid = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int status_exclusion_item_valid = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int status_exclusion_list_notvalid = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int status_exclusion_list_valid = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int status_hostname_empty = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int status_hostname_notvalid = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int status_hostname_valid = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int status_pac_cannot_retrieve_uri = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int status_pac_empty_invalid = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int status_pac_invalid_uri = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int status_pac_valid = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int status_pac_valid_uri = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int status_port_empty = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int status_port_notvalid = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int status_port_valid = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int status_proxy_disabled = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int status_proxy_enabled = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int status_proxy_mobile_disabled = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int status_proxy_not_reachable = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int status_proxy_not_valid_informations = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int status_proxy_reachable = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int status_title_checking = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int status_title_enabled = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int status_title_invalid_host = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int status_title_invalid_pac = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int status_title_invalid_port = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int status_title_not_enabled = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int status_title_not_reachable = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int status_title_web_not_reachable = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int status_web_not_reachable = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int status_web_reachable = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int status_wifi_enabled = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int status_wifi_enabled_disconnected = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int status_wifi_not_enabled = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int status_wifi_not_selected = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int status_wifi_selected = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int wifi_security_eap = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int wifi_security_none = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int wifi_security_psk_generic = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int wifi_security_short_eap = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int wifi_security_short_psk_generic = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int wifi_security_short_wep = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int wifi_security_short_wpa = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int wifi_security_short_wpa2 = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int wifi_security_short_wpa_wpa2 = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int wifi_security_wep = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int wifi_security_wpa = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int wifi_security_wpa2 = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int wifi_security_wpa_wpa2 = 2130968641;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] WifiEncryptionState = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int WifiEncryptionState_state_encrypted = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
